server:
    port: 8101
spring:
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            discovery:
                ip: 127.0.0.1
                port: ${server.port}
                namespace: test
                log-name: ./logs/
        loadbalancer:
            enabled: true
    application:
        name: cloud-provider